2025-01-28 17:04:51.856124: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-01-28 17:04:51.873905: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1738101891.892410 1611794 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1738101891.898082 1611794 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-01-28 17:04:51.917769: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Using backend: tensorflow
Other supported backends: tensorflow.compat.v1, pytorch, jax, paddle.
paddle supports more examples now and is recommended.
Enable just-in-time compilation with XLA.

Disable just-in-time compilation with XLA.
ERROR:root:ERROR: MATLAB type not supported: qmustatistics, (uint32)
ERROR:root:ERROR: MATLAB type not supported: lovenumbers, (uint32)
ERROR:root:ERROR: MATLAB type not supported: rotational, (uint32)
ERROR:root:ERROR: MATLAB type not supported: solidearthsettings, (uint32)
2025-01-28 17:04:56.853516: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
I0000 00:00:1738101896.853763 1611794 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 31134 MB memory:  -> device: 0, name: Tesla V100-SXM2-32GB, pci bus id: 0000:61:00.0, compute capability: 7.0
Traceback (most recent call last):
  File "/panfs/ccds02/nobackup/people/achartra/GreenlandScape/GreenlandScape_PINNICLE/Ryder_MOLHO_double2.py", line 97, in <module>
    experiment.train()
  File "/panfs/ccds02/nobackup/people/achartra/PINNICLE/pinnicle/pinn.py", line 181, in train
    self._loss_history, self._train_state = self.model.train(iterations=iterations,
  File "/home/achartra/.conda/envs/PINNICLEenv/lib/python3.10/site-packages/deepxde/utils/internal.py", line 22, in wrapper
    result = f(*args, **kwargs)
  File "/home/achartra/.conda/envs/PINNICLEenv/lib/python3.10/site-packages/deepxde/model.py", line 657, in train
    self._train_sgd(iterations, display_every)
  File "/home/achartra/.conda/envs/PINNICLEenv/lib/python3.10/site-packages/deepxde/model.py", line 684, in _train_sgd
    self._test()
  File "/home/achartra/.conda/envs/PINNICLEenv/lib/python3.10/site-packages/deepxde/model.py", line 871, in _test
    display.training_display(self.train_state)
  File "/home/achartra/.conda/envs/PINNICLEenv/lib/python3.10/site-packages/deepxde/display.py", line 42, in __call__
    self.print_one(
  File "/home/achartra/.conda/envs/PINNICLEenv/lib/python3.10/site-packages/deepxde/display.py", line 30, in print_one
    sys.stdout.flush()
OSError: [Errno 5] Input/output error
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
OSError: [Errno 5] Input/output error
